Repository Team-Ampersand/Dotori-client-v2, pull requests merged in 2023-03, with the labels that each got.

#18 global style 수정
  .prettierrc
  src/styles/globals.tsx
Labels: ⚡Type: Simple

#17 Add 문의하기
  src/components/Home/atoms/Script/SomeScript.tsx
  src/pages/home.tsx
Labels: ✨ Type: Feature

#19 Fix global style
  src/styles/globals.tsx
Labels: ⚡Type: Simple

#21 Fix noticeItem width
  src/components/Common/atoms/Items/NoticeItem/style.ts
Labels: ⚡Type: Simple

#22 Feature/common header
  src/components/Common/organisms/CommonHeader/index.tsx
  src/components/Common/organisms/CommonHeader/style.ts
  src/components/Massage/organisms/MassageHeader/index.tsx
  src/components/Massage/organisms/index.ts
  src/components/SelfStudy/organisms/SelfStudyHeader/index.tsx
  src/components/SelfStudy/organisms/SelfStudyHeader/style.ts
  src/components/SelfStudy/organisms/index.ts
  src/pages/massage.tsx
  src/pages/selfstudy.tsx
Labels: ⚡Type: Simple

#23 Fix modalHeader 파일경로
  src/components/Common/atoms/ModalHeader/index.tsx
  src/components/Common/atoms/ModalHeader/style.ts
Labels: ⚡Type: Simple

#25 Fix boardItem width
  src/assets/svg/HanbergerIcon.tsx
  src/assets/svg/MoonIcon.tsx
  src/assets/svg/PenIcon.tsx
  src/assets/svg/index.ts
  src/components/Common/atoms/Buttons/DarkModeBtn/style.ts
  src/components/Common/atoms/Buttons/LogoutButton/style.ts
  src/components/Common/atoms/Items/NoticeItem/style.ts
  src/components/Common/atoms/Items/SidebarItem/style.ts
  src/components/Common/molecules/SidebarList/style.ts
  src/components/Common/organisms/NavigationDrawer/index.tsx
  src/components/Common/organisms/NavigationDrawer/style.ts
  src/components/Common/organisms/Sidebar/style.ts
  src/components/Common/templates/MainTemplates/style.ts
  src/components/Home/atoms/MenuOption/index.tsx
  src/components/Home/atoms/MenuOption/style.ts
  src/components/Home/molecules/ApplyBox/index.tsx
  src/components/Home/molecules/ApplyBox/style.ts
  src/components/Home/molecules/MenuModal/index.tsx
  src/components/Home/molecules/MenuModal/style.ts
  src/components/Home/molecules/PenaltyModal/index.tsx
  src/components/Home/molecules/PenaltyModal/style.ts
  src/components/Home/molecules/ProfileImgModal/index.tsx
  src/components/Home/molecules/ProfileImgModal/style.ts
  src/components/Home/organisms/MealBoard/index.tsx
  src/components/Home/organisms/MealBoard/style.ts
  src/components/Home/organisms/NoticeBoard/style.ts
  src/components/Home/organisms/Profile/index.tsx
  src/components/Home/organisms/Profile/style.ts
  src/components/Home/organisms/TimeBoard/index.tsx
  src/components/Home/organisms/TimeBoard/style.ts
  src/components/Home/templates/HomeTemplates/style.ts
  src/types/Modals.ts
  src/types/Sidebar.ts
  src/utils/ChangeProfileModalcon.tsx
Labels: ⚡Type: Simple

#30 Feature/common check modal
  src/components/Common/molecules/CommonDelModal/index.tsx
  src/components/Common/molecules/CommonDelModal/style.ts
  src/components/Penalty/atoms/PenaltyListModalItem/index.tsx
  src/types/Modals.ts
Labels: ⚡Type: Simple

#33 Update homPageImage rendering
  package.json
  src/components/Home/organisms/TimeBoard/index.tsx
  yarn.lock
Labels: ⚡Type: Simple

#35 Fix : ModalOverayWrapper, NavigationDrawer
  src/components/Common/atoms/Wrappers/ModalOverayWrapper/style.ts
  src/components/Common/molecules/CommonCheckModal/index.tsx
  src/components/Common/organisms/NavigationDrawer/index.tsx
  src/components/Common/organisms/NavigationDrawer/style.ts
  src/components/Home/molecules/ApplyModifyModal/index.tsx
  src/components/Home/molecules/PenaltyModal/index.tsx
  src/components/Home/molecules/ProfileImgModal/index.tsx
  src/components/Penalty/molecules/PenaltyListModal/index.tsx
  src/components/Penalty/molecules/PenaltyRecordMenuModal/index.tsx
  src/components/Penalty/molecules/PenaltyRecordModal/index.tsx
Labels: ⚡Type: Simple

#36 Update 삭제아이콘
  src/assets/svg/XIcon.tsx
  src/assets/svg/XmarkIcon.tsx
  src/assets/svg/index.ts
  src/components/Common/atoms/Inputs/AuthInput/index.tsx
  src/components/Common/atoms/Inputs/AuthInput/style.ts
  src/components/Penalty/molecules/PenaltyRecordModal/index.tsx
Labels: ⚡Type: Simple

#38 Fix apiClient, global style
  src/styles/globals.tsx
  src/utils/Config/Config.json
  src/utils/Libs/apiClient.ts
  src/utils/Libs/getRefresh.ts
Labels: ⚡Type: Simple

#37 Feature/response/selfstudy
  src/assets/svg/CupIcon.tsx
  src/assets/svg/DownloadIcon.tsx
  src/assets/svg/FilterIcon.tsx
  src/assets/svg/index.ts
  src/components/Common/atoms/Wrappers/ModalOverayWrapper/style.ts
  src/components/Common/molecules/ApplicationItem/style.ts
  src/components/Common/molecules/NullApplicationItem/style.ts
  src/components/Common/molecules/SearchFilter/index.tsx
  src/components/Common/molecules/SearchFilter/style.ts
  src/components/Common/organisms/CommonHeader/index.tsx
  src/components/Common/organisms/CommonHeader/style.ts
  src/components/Massage/organisms/MassageTable/index.tsx
  src/components/Massage/organisms/MassageTable/style.ts
  src/components/Massage/templates/MassageTemplates/style.ts
  src/components/SelfStudy/organisms/SelfStudyTable/index.tsx
  src/components/SelfStudy/organisms/SelfStudyTable/style.ts
  src/components/SelfStudy/templates/SelfstudyTemplates/style.ts
  src/recoilAtoms/recoilAtomContainer.ts
  src/types/Filter.ts
Labels: 🎨 Type: Publishing

#41 Update 홈페이지 기능구현
  src/api/massage.ts
  src/api/notice.ts
  src/api/selfStudy.ts
  src/assets/png/Dotori3D.png
  src/assets/png/Dotori3DDark.png
  src/assets/png/shadow.png
  src/components/Common/atoms/Items/SidebarItem/index.tsx
  src/components/Common/atoms/Items/SidebarItem/style.ts
  src/components/Common/atoms/Wrappers/ModalOverayWrapper/style.ts
  src/components/Common/molecules/SidebarList/index.tsx
  src/components/Common/organisms/Sidebar/index.tsx
  src/components/Home/atoms/PenaltyItem/index.tsx
  src/components/Home/atoms/PenaltyItem/style.ts
  src/components/Home/atoms/Script/SomeScript.tsx
  src/components/Home/molecules/ApplyBox/index.tsx
  src/components/Home/molecules/ApplyBox/style.ts
  src/components/Home/molecules/ChannelBtn/index.tsx
  src/components/Home/molecules/MenuModal/index.tsx
  src/components/Home/molecules/PenaltyModal/index.tsx
  src/components/Home/molecules/PenaltyModal/style.ts
  src/components/Home/molecules/ProfileImgModal/index.tsx
  src/components/Home/molecules/ProfileImgModal/style.ts
  src/components/Home/organisms/MassageBoard/index.tsx
  src/components/Home/organisms/MealBoard/style.ts
  src/components/Home/organisms/NoticeBoard/index.tsx
  src/components/Home/organisms/NoticeBoard/style.ts
  src/components/Home/organisms/Profile/index.tsx
  src/components/Home/organisms/Profile/style.ts
  src/components/Home/organisms/SelfStudyBoard/index.tsx
  src/components/Home/organisms/TimeBoard/index.tsx
  src/components/Home/organisms/TimeBoard/style.ts
  src/components/Home/templates/HomeTemplates/style.ts
  src/components/Penalty/atoms/PenaltyListModalItem/index.tsx
  src/components/Penalty/molecules/PenaltyListModal/index.tsx
  src/hooks/useDecode.ts
  src/hooks/useRole.ts
  src/pages/home.tsx
  src/pages/massage.tsx
  src/pages/penalty.tsx
  src/pages/selfstudy.tsx
  src/recoilAtoms/recoilAtomContainer.ts
  src/types/Home.ts
  src/types/List.ts
  src/types/Modals.ts
  src/types/Role.ts
  src/types/Sidebar.ts
  src/utils/Libs/getRole.ts
  src/utils/Libs/requestUrls.ts
Labels: ✨ Type: Feature

#40 Add 프로모션 페이지
  package.json
  src/components/Promotion/molecules/DecsPart/index.tsx
  src/components/Promotion/molecules/DecsPart/style.ts
  src/components/Promotion/organisms/PromotionOrganisms/index.tsx
  src/components/Promotion/organisms/PromotionOrganisms/style.ts
  src/components/Promotion/templates/PromotionTemplates/style.ts
  src/pages/index.tsx
  src/types/Modals.ts
  yarn.lock
Labels: ✨ Type: Feature, 🎨 Type: Publishing

#46 Add : 404 page
  src/api/massage.ts
  src/api/selfStudy.ts
  src/assets/png/404.png
  src/components/ NotFound/organisms/NotFoundOrganisms/index.tsx
  src/components/ NotFound/organisms/NotFoundOrganisms/style.ts
  src/components/Common/atoms/Inputs/AuthInput/index.tsx
  src/components/Home/organisms/MassageBoard/index.tsx
  src/components/Home/organisms/SelfStudyBoard/index.tsx
  src/components/SignUp/molecules/StuInfo/index.tsx
  src/pages/404.tsx
  src/types/Home.ts
Labels: ✨ Type: Feature, 📬 Type: API, ⚡Type: Simple, 🎨 Type: Publishing

#48 Update : 자습신청, 안마의자 신청시간에 랜더링설정
  src/components/Common/atoms/Inputs/AuthInput/style.ts
  src/components/Common/organisms/NavigationDrawer/index.tsx
  src/components/Home/organisms/MassageBoard/index.tsx
  src/components/Home/organisms/SelfStudyBoard/index.tsx
  src/components/Home/organisms/TimeBoard/index.tsx
  src/components/NotFound/organisms/NotFoundOrganisms/index.tsx
  src/components/NotFound/organisms/NotFoundOrganisms/style.ts
  src/components/SignIn/organisms/SignInForm/index.tsx
  src/components/SignUp/molecules/EmailCheck/index.tsx
  src/components/SignUp/molecules/PasswordCheck/index.tsx
  src/components/SignUp/molecules/StuInfo/index.tsx
  src/components/SignUp/molecules/StuInfo/style.ts
  src/components/SignUp/organisms/SignUpForm/index.tsx
  src/pages/404.tsx
  src/pages/home.tsx
  src/utils/Libs/getRefresh.ts
Labels: ✨ Type: Feature, ⚡Type: Simple

#49 Fix token Bearer
  src/api/member.ts
  src/components/SignUp/molecules/StuInfo/index.tsx
  src/components/SignUp/molecules/StuInfo/style.ts
  src/pages/signin.tsx
  src/pages/signup.tsx
  src/utils/Libs/getRole.ts
  src/utils/Libs/setToken.ts
Labels: 🔨 Type: Refector

#50 Fix getRole
  src/assets/json/role.json
  src/types/Role.ts
  src/utils/Libs/getRole.ts
Labels: ⚡Type: Simple

#47 Feature/selfstudy
  src/api/massage.ts
  src/api/selfStudy.ts
  src/components/Common/atoms/Items/FilterItem/index.tsx
  src/components/Common/molecules/ApplicationItem/index.tsx
  src/components/Common/molecules/SearchFilter/index.tsx
  src/components/Massage/molecules/MassageList/index.tsx
  src/components/Massage/organisms/MassageTable/index.tsx
  src/components/Massage/templates/MassageTemplates/style.ts
  src/components/Penalty/organisms/PenaltyTable/index.tsx
  src/components/SelfStudy/atoms/SelfstudyCheck/SelfstudyCheck.tsx
  src/components/SelfStudy/molecules/SelfStudyList/index.tsx
  src/components/SelfStudy/organisms/SelfStudyTable/index.tsx
  src/components/SelfStudy/templates/SelfstudyTemplates/style.ts
  src/hooks/useDidMountEffect.ts
  src/pages/massage.tsx
  src/pages/selfstudy.tsx
  src/recoilAtoms/recoilAtomContainer.ts
  src/types/Checkbox.ts
  src/types/Filter.ts
  src/types/List.ts
  src/types/Massage.ts
  src/types/Selfstudy.ts
  src/types/index.ts
  src/utils/Libs/requestUrls.ts
Labels: ✨ Type: Feature

#51 🔀 Un-configured Host 문제 수정
  next.config.js
Labels: ⚡Type: Simple

#53 Update : toast darkMode
  src/pages/_app.tsx
Labels: ⚡Type: Simple

#58 Fix message, selfStudy Board
  src/api/massage.ts
  src/api/selfStudy.ts
  src/components/Home/organisms/MassageBoard/index.tsx
  src/components/Home/organisms/NoticeBoard/index.tsx
  src/components/Home/organisms/SelfStudyBoard/index.tsx
Labels: 🔨 Type: Refector

#63 🔀Common Header title 개선
  src/components/Common/organisms/CommonHeader/index.tsx
Labels: ⚡Type: Simple, 🪛 Type: Performance

#60 규정위반 페이지 기능구현
  src/api/penalty.ts
  src/assets/svg/PlusIcon.tsx
  src/assets/svg/SearchIcon.tsx
  src/components/Common/atoms/Calendar/index.tsx
  src/components/Common/atoms/Calendar/style.ts
  src/components/Common/molecules/SearchFilter/index.tsx
  src/components/Common/organisms/CommonHeader/index.tsx
  src/components/Home/organisms/MealBoard/index.tsx
  src/components/Home/organisms/TimeBoard/index.tsx
  src/components/Penalty/atoms/PenaltyCheck/index.tsx
  src/components/Penalty/atoms/PenaltyItem/Style.ts
  src/components/Penalty/atoms/PenaltyItem/index.tsx
  src/components/Penalty/atoms/PenaltyListModalItem/index.tsx
  src/components/Penalty/molecules/PenaltyList/index.tsx
  src/components/Penalty/molecules/PenaltyListModal/index.tsx
  src/components/Penalty/molecules/PenaltyListModal/style.ts
  src/components/Penalty/molecules/PenaltyRecordMenuModal/index.tsx
  src/components/Penalty/molecules/PenaltyRecordModal/index.tsx
  src/components/Penalty/molecules/PenaltyRecordModal/style.ts
  src/components/Penalty/organisms/PenaltyTable/index.tsx
  src/pages/penalty.tsx
  src/recoilAtoms/recoilAtomContainer.ts
  src/types/Filter.ts
  src/types/Modals.ts
  src/types/Penalty.ts
  src/utils/Libs/requestUrls.ts
  src/utils/Libs/returnPenaltyValues.ts
  src/utils/getDate.ts
  src/utils/todayDate.ts
Labels: ✨ Type: Feature

#65 Update 로그인전 패스워드 체크 페이지
  src/api/member.ts
  src/components/ChangePasswd/organisms/ChangePasswdForm/index.tsx
  src/components/ChangePasswd/organisms/PasswdEmailCheck/index.tsx
  src/components/Common/molecules/EmailCheck/index.tsx
  src/components/Common/molecules/EmailCheck/style.ts
  src/components/Common/organisms/Sidebar/index.tsx
  src/components/Home/organisms/NoticeBoard/index.tsx
  src/components/Home/organisms/NoticeBoard/style.ts
  src/components/Home/organisms/Profile/index.tsx
  src/components/Home/organisms/TimeBoard/index.tsx
  src/components/Promotion/molecules/DecsPart/index.tsx
  src/components/Promotion/molecules/DecsPart/style.ts
  src/components/SignUp/organisms/SignUpForm/index.tsx
  src/pages/changePasswd.tsx
  src/recoilAtoms/recoilAtomContainer.ts
  src/types/Home.ts
  src/utils/Libs/requestUrls.ts
Labels: ✨ Type: Feature

#66 Add : authPasswordChange api
  src/api/member.ts
  src/components/ChangePasswd/organisms/ChangePasswdForm/index.tsx
  src/components/Common/molecules/EmailCheck/index.tsx
  src/pages/changePasswd.tsx
  src/recoilAtoms/recoilAtomContainer.ts
  src/utils/Libs/requestUrls.ts
Labels: ⚡Type: Simple
