Repository Team-Ampersand/Dotori-client-v2, pull requests merged in 2023-04, with the labels that each got.

#68 Add middleware
  src/middleware.ts
  src/pages/home.tsx
  src/pages/massage.tsx
  src/pages/penalty.tsx
  src/pages/selfstudy.tsx
  src/pages/signin.tsx
  src/pages/signup.tsx
Labels: 🔨 Type: Refector

#69 Add : CEOHead
  src/components/Common/atoms/SEOHead/index.tsx
  src/pages/404.tsx
  src/pages/_document.tsx
  src/pages/changePasswd.tsx
  src/pages/home.tsx
  src/pages/index.tsx
  src/pages/massage.tsx
  src/pages/penalty.tsx
  src/pages/selfstudy.tsx
  src/pages/signin.tsx
  src/pages/signup.tsx
Labels: ✨ Type: Feature

#54 🔀공지사항 페이지 제작
  src/api/notice.ts
  src/assets/svg/EditPencilIcon.tsx
  src/assets/svg/PaperIcon.tsx
  src/assets/svg/TrashCan.tsx
  src/assets/svg/XmarkIcon.tsx
  src/assets/svg/index.ts
  src/components/Common/atoms/Items/NoticeItem/index.tsx
  src/components/Home/organisms/NoticeBoard/index.tsx
  src/components/Notice/atoms/NoticeOptionBtn/index.tsx
  src/components/Notice/atoms/NoticeOptionBtn/style.ts
  src/components/Notice/molecules/BottomBtnBox/index.tsx
  src/components/Notice/molecules/BottomBtnBox/style.ts
  src/components/Notice/molecules/ContentHeader/index.tsx
  src/components/Notice/molecules/ContentHeader/style.ts
  src/components/Notice/molecules/ImgForm/index.tsx
  src/components/Notice/molecules/ImgForm/style.ts
  src/components/Notice/molecules/ListHeader/index.tsx
  src/components/Notice/molecules/ListHeader/style.ts
  src/components/Notice/molecules/WriteForm/index.tsx
  src/components/Notice/molecules/WriteForm/style.ts
  src/components/Notice/organisms/NoticeContent/index.tsx
  src/components/Notice/organisms/NoticeContent/style.ts
  src/components/Notice/organisms/NoticeEmpty/index.tsx
  src/components/Notice/organisms/NoticeEmpty/style.ts
  src/components/Notice/organisms/NoticeList/index.tsx
  src/components/Notice/organisms/NoticeList/style.ts
  src/components/Notice/organisms/NoticeWrite/index.tsx
  src/components/Notice/organisms/NoticeWrite/style.ts
  src/components/Notice/templates/NoticeTemplate/style.ts
  src/pages/_app.tsx
  src/pages/notice/[boardId].tsx
  src/pages/notice/index.tsx
  src/recoilAtoms/recoilAtomContainer.ts
  src/types/Home.ts
  src/types/Sidebar.ts
  src/types/common/userRole.ts
  src/types/components/NoticePage.ts
  src/utils/Libs/apiClient.ts
  src/utils/Libs/getToken.ts
  src/utils/Libs/requestRole.ts
  src/utils/Libs/requestUrls.ts
Labels: ✨ Type: Feature, 🎨 Type: Publishing

#72 Fix : middleware
  src/components/Common/atoms/SEOHead/index.tsx
  src/components/SignIn/organisms/SignInForm/index.tsx
  src/middleware.ts
  src/pages/404.tsx
  src/pages/changePasswd.tsx
  src/pages/home.tsx
  src/pages/index.tsx
  src/pages/massage.tsx
  src/pages/penalty.tsx
  src/pages/selfstudy.tsx
  src/pages/signin.tsx
  src/pages/signup.tsx
Labels: 🔨 Type: Refector

#74 🔀 공지사항 페이지 swr config 추가
  src/pages/notice/[boardId].tsx
  src/pages/notice/index.tsx
Labels: ⚡Type: Simple

#61 🔀기상음악 페이지 제작
  src/api/music.ts
  src/assets/svg/MusicNoteIcon.tsx
  src/assets/svg/NewPageIcon.tsx
  src/assets/svg/index.ts
  src/components/Song/molecules/ListHeader/index.tsx
  src/components/Song/molecules/NoticeModal/index.tsx
  src/components/Song/molecules/NoticeModal/style.ts
  src/components/Song/molecules/SongForm/index.tsx
  src/components/Song/molecules/SongForm/style.ts
  src/components/Song/molecules/SongItem/index.tsx
  src/components/Song/molecules/SongItem/style.ts
  src/components/Song/organisms/SongList/index.tsx
  src/components/Song/organisms/SongList/style.ts
  src/components/Song/organisms/SongRightLayer/index.tsx
  src/components/Song/organisms/SongRightLayer/style.ts
  src/components/Song/template/style.ts
  src/pages/song.tsx
  src/recoilAtoms/recoilAtomContainer.ts
  src/types/components/SongPage.ts
  src/utils/Libs/requestUrls.ts
Labels: ✨ Type: Feature, 🎨 Type: Publishing

#97 Fix HomePage, PasswdChangePage Issues
  src/api/member.ts
  src/components/ChangePasswd/organisms/ChangePasswdForm/index.tsx
  src/components/Common/atoms/SEOHead/index.tsx
  src/components/Common/molecules/EmailCheck/index.tsx
  src/components/Home/molecules/ApplyBox/index.tsx
  src/components/Home/organisms/Profile/index.tsx
  src/components/Home/organisms/TimeBoard/style.ts
  src/components/SignUp/molecules/PasswordCheck/index.tsx
Labels: 🐞 Type: Bug

#106 🔀 Calendar style 수정
  src/components/Common/atoms/Calendar/style.ts
Labels: 1️⃣ Priority: High, 🎨 Type: Publishing

#109 🔀 기상음악 페이지 디자인 수정
  src/components/Common/organisms/CommonHeader/index.tsx
  src/components/Common/organisms/CommonHeader/style.ts
  src/components/Notice/molecules/ListHeader/style.ts
  src/components/Notice/organisms/NoticeList/index.tsx
  src/components/Notice/organisms/NoticeList/style.ts
  src/components/Notice/templates/NoticeTemplate/style.ts
  src/components/Song/molecules/ListHeader/index.tsx
  src/components/Song/molecules/SongForm/style.ts
  src/components/Song/molecules/SongItem/index.tsx
  src/components/Song/molecules/SongItem/style.ts
  src/components/Song/organisms/SongList/style.ts
  src/components/Song/organisms/SongModal/index.tsx
  src/components/Song/organisms/SongRightLayer/style.ts
  src/components/Song/template/style.ts
  src/pages/song.tsx
Labels: 1️⃣ Priority: High, 📬 Type: API, 🎨 Type: Publishing

#115 🔀 공지사항 이슈 수정
  src/components/Home/organisms/SelfStudyBoard/index.tsx
  src/components/Notice/molecules/ContentHeader/index.tsx
  src/components/Notice/molecules/ListHeader/index.tsx
  src/components/Notice/molecules/WriteForm/style.ts
  src/components/Notice/organisms/NoticeEmpty/index.tsx
  src/components/Notice/organisms/NoticeEmpty/style.ts
  src/components/Notice/organisms/NoticeList/index.tsx
  src/components/Notice/organisms/NoticeList/style.ts
  src/components/Notice/templates/NoticeTemplate/style.ts
  src/pages/notice/[boardId].tsx
  src/pages/notice/index.tsx
Labels: 0️⃣ Priority: Critical, 🎨 Type: Publishing, 🪛 Type: Performance

#129 Fix Home, PasswdChange
  src/api/member.ts
  src/assets/data/RegexsData.ts
  src/assets/data/SidebarMenuData.ts
  src/assets/png/Gradation.png
  src/components/ChangePasswd/organisms/ChangePasswdForm/index.tsx
  src/components/Common/molecules/EmailCheck/index.tsx
  src/components/Home/molecules/ApplyBox/index.tsx
  src/components/Home/organisms/Profile/index.tsx
  src/components/Home/organisms/TimeBoard/index.tsx
  src/components/Home/organisms/TimeBoard/style.ts
  src/components/SignIn/organisms/SignInForm/index.tsx
  src/components/SignUp/molecules/PasswordCheck/index.tsx
  src/components/SignUp/molecules/StuInfo/index.tsx
  src/pages/home.tsx
  src/pages/signup.tsx
  src/types/Assets.ts
  src/types/index.ts
Labels: 🐞 Type: Bug

#130 🔀 기상음악 이슈 수정
  src/api/music.ts
  src/components/Song/molecules/NoticeModal/index.tsx
  src/components/Song/molecules/SongForm/style.ts
  src/components/Song/molecules/SongItem/index.tsx
  src/components/Song/molecules/SongItem/style.ts
  src/components/Song/organisms/SongList/style.ts
  src/components/Song/organisms/SongModal/index.tsx
  src/components/Song/template/style.ts
  src/pages/_app.tsx
  src/pages/song.tsx
Labels: 0️⃣ Priority: Critical, 🎨 Type: Publishing, 🪛 Type: Performance

#132 SearchFiler issue, authinput 적용
  src/assets/svg/SearchIcon.tsx
  src/components/Common/atoms/Inputs/AuthInput/index.tsx
  src/components/Common/atoms/Inputs/AuthInput/style.ts
  src/components/Common/atoms/Items/FilterItem/index.tsx
  src/components/Common/molecules/SearchFilter/index.tsx
  src/components/Common/molecules/SearchFilter/style.ts
  src/components/Penalty/organisms/PenaltyTable/index.tsx
  src/components/SelfStudy/organisms/SelfStudyTable/index.tsx
  src/types/Filter.ts
  src/types/Inputs.ts
Labels: 🔨 Type: Refector, ⚡Type: Simple

#135 🔀 공지사항 디자인 수정
  src/assets/svg/PaperIcon.tsx
  src/components/Notice/molecules/ListHeader/index.tsx
  src/components/Notice/molecules/ListHeader/style.ts
  src/components/Notice/organisms/NoticeContent/index.tsx
Labels: 3️⃣ Priority: Low, 🎨 Type: Publishing

#136 PeanltyPage Response
  src/assets/svg/EllipsisVerticalIcon.tsx
  src/assets/svg/index.ts
  src/components/Penalty/atoms/PenaltyItem/Style.ts
  src/components/Penalty/atoms/PenaltyItem/index.tsx
  src/components/Penalty/molecules/PenaltyListModal/style.ts
  src/components/Penalty/molecules/PenaltyRecordMenuModal/index.tsx
  src/components/Penalty/molecules/PenaltyRecordMenuModal/style.ts
  src/components/Penalty/molecules/PenaltyRecordModal/style.ts
  src/components/Penalty/organisms/PenaltyTable/index.tsx
  src/components/Penalty/organisms/PenaltyTable/style.ts
  src/components/Penalty/templates/PenaltyTemplates/style.ts
Labels: 🎨 Type: Publishing

#142 Add: HomePage, AuthPage issues
  src/assets/svg/EllipsisVerticalIcon.tsx
  src/assets/svg/index.ts
  src/components/Common/atoms/Buttons/AuthButton/index.tsx
  src/components/Common/atoms/Buttons/AuthButton/style.ts
  src/components/Common/atoms/Buttons/LogoutButton/index.tsx
  src/components/Common/atoms/Inputs/AuthInput/style.ts
  src/components/Common/atoms/Wrappers/AuthWrapper/style.ts
  src/components/Common/molecules/CommonCheckModal/index.tsx
  src/components/Home/atoms/MenuOption/index.tsx
  src/components/Home/atoms/MenuOption/style.ts
  src/components/Home/molecules/ApplyBox/index.tsx
  src/components/Home/molecules/ApplyBox/style.ts
  src/components/Home/molecules/ApplyModifyModal/index.tsx
  src/components/Home/molecules/MenuModal/index.tsx
  src/components/Home/molecules/PenaltyModal/index.tsx
  src/components/Home/molecules/ProfileImgModal/index.tsx
  src/components/Home/organisms/MassageBoard/index.tsx
  src/components/Home/organisms/MealBoard/index.tsx
  src/components/Home/organisms/MealBoard/style.ts
  src/components/Home/organisms/NoticeBoard/index.tsx
  src/components/Home/organisms/Profile/index.tsx
  src/components/Home/organisms/SelfStudyBoard/index.tsx
  src/components/Penalty/atoms/PenaltyItem/Style.ts
  src/components/Penalty/atoms/PenaltyItem/index.tsx
  src/components/Penalty/molecules/PenaltyListModal/style.ts
  src/components/Penalty/molecules/PenaltyRecordMenuModal/index.tsx
  src/components/Penalty/molecules/PenaltyRecordMenuModal/style.ts
  src/components/Penalty/molecules/PenaltyRecordModal/style.ts
  src/components/Penalty/organisms/PenaltyTable/index.tsx
  src/components/Penalty/organisms/PenaltyTable/style.ts
  src/components/Penalty/templates/PenaltyTemplates/style.ts
  src/components/SignIn/organisms/SignInForm/index.tsx
  src/pages/_app.tsx
  src/pages/home.tsx
  src/types/Home.ts
  src/types/Modals.ts
  src/utils/Libs/clearCache.ts
  src/utils/Libs/logout.ts
Labels: 🔨 Type: Refector, 🎨 Type: Publishing, 🪛 Type: Performance

#154 🔀 학생정보 페이지 추가
  src/api/selfStudy.ts
  src/api/stuInfo.ts
  src/assets/data/RoleData.ts
  src/assets/svg/BookBenIcon.tsx
  src/assets/svg/EditPencilIcon.tsx
  src/components/Notice/molecules/WriteForm/index.tsx
  src/components/StuInfo/molecules/EditInput/index.tsx
  src/components/StuInfo/molecules/EditInput/style.ts
  src/components/StuInfo/molecules/EditRadioBtn/index.tsx
  src/components/StuInfo/molecules/EditRadioBtn/style.ts
  src/components/StuInfo/molecules/StuInfoItem/index.tsx
  src/components/StuInfo/molecules/StuInfoItem/style.ts
  src/components/StuInfo/organisms/EditModal/index.tsx
  src/components/StuInfo/organisms/EditModal/style.ts
  src/components/StuInfo/organisms/StuInfoForm/index.tsx
  src/components/StuInfo/organisms/StuInfoForm/style.ts
  src/components/StuInfo/organisms/StuInfoList/index.tsx
  src/components/StuInfo/organisms/StuInfoList/style.ts
  src/components/StuInfo/template/style.ts
  src/pages/studsDetail.tsx
  src/recoilAtoms/recoilAtomContainer.ts
  src/types/Role.ts
  src/types/components/StuInfoPage.ts
  src/utils/Libs/requestRole.ts
  src/utils/Libs/requestUrls.ts
Labels: ✨ Type: Feature, 0️⃣ Priority: Critical, 🪛 Type: Performance
