Repository Team-Ampersand/Dotori-client-v2, pull requests merged in 2023-05, with the labels that each got.

#174 Main -> Develop
  src/api/selfStudy.ts
  src/api/stuInfo.ts
  src/assets/data/RoleData.ts
  src/assets/svg/BookBenIcon.tsx
  src/assets/svg/EditPencilIcon.tsx
  src/assets/svg/PaperIcon.tsx
  src/components/Common/atoms/Buttons/AuthButton/index.tsx
  src/components/Common/atoms/Buttons/AuthButton/style.ts
  src/components/Common/atoms/Buttons/DarkModeBtn/index.tsx
  src/components/Common/atoms/Buttons/DarkModeBtn/style.ts
  src/components/Common/atoms/Buttons/LogoutButton/index.tsx
  src/components/Common/atoms/Inputs/AuthInput/style.ts
  src/components/Common/atoms/Wrappers/AuthWrapper/style.ts
  src/components/Common/molecules/CommonCheckModal/index.tsx
  src/components/Common/molecules/SearchFilter/index.tsx
  src/components/Home/atoms/MenuOption/index.tsx
  src/components/Home/atoms/MenuOption/style.ts
  src/components/Home/molecules/ApplyBox/index.tsx
  src/components/Home/molecules/ApplyBox/style.ts
  src/components/Home/molecules/ApplyModifyModal/index.tsx
  src/components/Home/molecules/MenuModal/index.tsx
  src/components/Home/molecules/PenaltyModal/index.tsx
  src/components/Home/molecules/ProfileImgModal/index.tsx
  src/components/Home/organisms/MassageBoard/index.tsx
  src/components/Home/organisms/MealBoard/index.tsx
  src/components/Home/organisms/MealBoard/style.ts
  src/components/Home/organisms/NoticeBoard/index.tsx
  src/components/Home/organisms/Profile/index.tsx
  src/components/Home/organisms/SelfStudyBoard/index.tsx
  src/components/Notice/molecules/ListHeader/index.tsx
  src/components/Notice/molecules/ListHeader/style.ts
  src/components/Notice/molecules/WriteForm/index.tsx
  src/components/Notice/organisms/NoticeContent/index.tsx
  src/components/SignIn/organisms/SignInForm/index.tsx
  src/components/StuInfo/molecules/EditInput/index.tsx
  src/components/StuInfo/molecules/EditInput/style.ts
  src/components/StuInfo/molecules/EditRadioBtn/index.tsx
  src/components/StuInfo/molecules/EditRadioBtn/style.ts
  src/components/StuInfo/molecules/StuInfoItem/index.tsx
  src/components/StuInfo/molecules/StuInfoItem/style.ts
  src/components/StuInfo/organisms/EditModal/index.tsx
  src/components/StuInfo/organisms/EditModal/style.ts
  src/components/StuInfo/organisms/StuInfoForm/index.tsx
  src/components/StuInfo/organisms/StuInfoForm/style.ts
  src/components/StuInfo/organisms/StuInfoList/index.tsx
  src/components/StuInfo/organisms/StuInfoList/style.ts
  src/components/StuInfo/template/style.ts
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/home.tsx
  src/pages/studsDetail.tsx
  src/recoilAtoms/recoilAtomContainer.ts
  src/types/Home.ts
  src/types/Modals.ts
  src/types/Role.ts
  src/types/components/StuInfoPage.ts
  src/utils/Libs/clearCache.ts
  src/utils/Libs/logout.ts
  src/utils/Libs/requestRole.ts
  src/utils/Libs/requestUrls.ts
Labels: 1️⃣ Priority: High

#175 msw 추가
  package.json
  public/mockServiceWorker.js
  src/mocks/browser.ts
  src/mocks/handler/[role]/board/[board_id]/get.ts
  src/mocks/handler/[role]/board/get.ts
  src/mocks/handler/[role]/massage/get.ts
  src/mocks/handler/[role]/music/get.ts
  src/mocks/handler/[role]/rule/get.ts
  src/mocks/handler/[role]/rule/stu_num/get.ts
  src/mocks/handler/[role]/self-study/info/get.ts
  src/mocks/handler/[role]/self-study/rank/get.ts
  src/mocks/handler/[role]/self-study/search/get.ts
  src/mocks/handler/auth/password/patch.ts
  src/mocks/handler/auth/patch.ts
  src/mocks/handler/auth/post.ts
  src/mocks/handler/auth/signup/post.ts
  src/mocks/handler/home/get.ts
  src/mocks/handler/index.ts
  src/mocks/handler/student-info/get.ts
  src/mocks/handler/student-info/search/get.ts
  src/mocks/index.ts
  src/mocks/server.ts
  src/mocks/utils/encodeBuffer.ts
  src/mocks/utils/jwtSignature.ts
  src/mocks/utils/mockApi.ts
  src/mocks/utils/mockJwt.ts
  src/pages/_app.tsx
  src/types/utils/mockJwt.ts
  src/utils/Libs/getRole.ts
  src/utils/Libs/requestUrls.ts
  yarn.lock
Labels: ✨ Type: Feature, 1️⃣ Priority: High, 📬 Type: API, ⚙ Type: Setting

#176 Fix Home, login Page Issues
  src/assets/svg/XmarkIcon.tsx
  src/components/Common/atoms/Inputs/AuthInput/index.tsx
  src/components/Home/atoms/MenuOption/style.ts
  src/components/SignIn/organisms/SignInForm/index.tsx
  src/middleware.ts
  src/pages/home.tsx
Labels: 🐞 Type: Bug, ⚡Type: Simple

#178 🔀 달력 요일 표기 변경
  src/components/Common/atoms/Calendar/index.tsx
Labels: 1️⃣ Priority: High, ⚡Type: Simple

#179 🔀 Deploy
  package.json
  public/mockServiceWorker.js
  src/assets/svg/XmarkIcon.tsx
  src/components/Common/atoms/Calendar/index.tsx
  src/components/Common/atoms/Inputs/AuthInput/index.tsx
  src/components/Home/atoms/MenuOption/style.ts
  src/components/SignIn/organisms/SignInForm/index.tsx
  src/middleware.ts
  src/mocks/browser.ts
  src/mocks/handler/[role]/board/[board_id]/get.ts
  src/mocks/handler/[role]/board/get.ts
  src/mocks/handler/[role]/massage/get.ts
  src/mocks/handler/[role]/music/get.ts
  src/mocks/handler/[role]/rule/get.ts
  src/mocks/handler/[role]/rule/stu_num/get.ts
  src/mocks/handler/[role]/self-study/info/get.ts
  src/mocks/handler/[role]/self-study/rank/get.ts
  src/mocks/handler/[role]/self-study/search/get.ts
  src/mocks/handler/auth/password/patch.ts
  src/mocks/handler/auth/patch.ts
  src/mocks/handler/auth/post.ts
  src/mocks/handler/auth/signup/post.ts
  src/mocks/handler/home/get.ts
  src/mocks/handler/index.ts
  src/mocks/handler/student-info/get.ts
  src/mocks/handler/student-info/search/get.ts
  src/mocks/index.ts
  src/mocks/server.ts
  src/mocks/utils/encodeBuffer.ts
  src/mocks/utils/jwtSignature.ts
  src/mocks/utils/mockApi.ts
  src/mocks/utils/mockJwt.ts
  src/pages/_app.tsx
  src/pages/home.tsx
  src/types/utils/mockJwt.ts
  src/utils/Libs/getRole.ts
  src/utils/Libs/requestUrls.ts
  yarn.lock
Labels: 🌏 Type: Deploy

#155 🔀 공지사항 작성자 null 이슈 수정
  src/assets/data/FilterMenuData.ts
  src/assets/data/RoleData.ts
  src/components/Common/atoms/Items/FilterItem/index.tsx
  src/components/Common/molecules/SearchFilter/index.tsx
  src/components/Common/molecules/SearchFilter/style.ts
  src/components/Notice/organisms/NoticeWrite/index.tsx
  src/components/StuInfo/organisms/StuInfoForm/index.tsx
  src/recoilAtoms/recoilAtomContainer.ts
  src/types/Role.ts
  src/types/common/userRole.ts
  src/types/components/StuInfoPage.ts
  src/utils/Libs/requestRole.ts
Labels: 🐞 Type: Bug, 1️⃣ Priority: High

#182 Add CommonPageWrapper
  src/components/Common/atoms/Wrappers/CommonPageWrapper/style.ts
  src/components/Home/organisms/Profile/style.ts
  src/components/Home/organisms/TimeBoard/style.ts
  src/components/Home/templates/HomeTemplates/style.ts
Labels: ⚡Type: Simple

#183 🔀 package-lock.json 삭제
  package-lock.json
Labels: ⚡Type: Simple

#184 🔀 CODEOWNERS 추가
  .github/CODEOWNERS
Labels: 📄 Type: Docs

#185 🔀 기상음악 페이지 트러블 슈팅
  src/api/music.ts
  src/assets/svg/MusicNoteIcon.tsx
  src/assets/svg/index.ts
  src/components/Common/atoms/Calendar/style.ts
  src/components/Common/molecules/CommonCheckModal/index.tsx
  src/components/Song/molecules/NoticeModal/style.ts
  src/components/Song/molecules/SongItem/index.tsx
  src/components/Song/molecules/SongItem/style.ts
  src/components/Song/organisms/SongList/index.tsx
  src/components/Song/organisms/SongList/style.ts
  src/components/Song/template/style.ts
  src/pages/song.tsx
  src/utils/Libs/preventEvent.ts
Labels: 1️⃣ Priority: High, 🎨 Type: Publishing
