Repository Team-Ampersand/Dotori-client-v2, pull requests merged in 2023-06, with the labels that each got.

#188 Penalty issue
  src/assets/data/PenaltyValuesData.ts
  src/components/Common/atoms/Calendar/index.tsx
  src/components/Common/organisms/CommonHeader/style.ts
  src/components/Home/molecules/PenaltyModal/index.tsx
  src/components/Penalty/atoms/PenaltyItem/index.tsx
  src/components/Penalty/molecules/PenaltyListModal/index.tsx
  src/components/Penalty/molecules/PenaltyRecordMenuModal/index.tsx
  src/components/Penalty/molecules/PenaltyRecordModal/index.tsx
  src/components/Penalty/organisms/PenaltyForm/index.tsx
  src/components/Penalty/organisms/PenaltyForm/style.ts
  src/components/Penalty/organisms/PenaltyTable/index.tsx
  src/components/Penalty/organisms/PenaltyTable/style.ts
  src/components/Penalty/templates/PenaltyTemplates/style.ts
  src/pages/penalty.tsx
Labels: 🔨 Type: Refector, 🪛 Type: Performance

#193 [#192] :: 🔀 Issue 템플릿 만들기
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/feature.yml
Labels: 📄 Type: Docs

#196 Refector 안마, 자습 신청불가케이스
  src/components/Home/organisms/MassageBoard/index.tsx
  src/components/Home/organisms/SelfStudyBoard/index.tsx
Labels: 🔨 Type: Refector
