Repository Team-Ampersand/Dotori-client-v2, pull requests merged in 2023-02, with the labels that each got.

#6 Add PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 📄 Type: Docs

#7 Add NoticeItem
  src/components/Common/atoms/Items/NoticeItem/index.tsx
  src/components/Common/atoms/Items/NoticeItem/style.ts
  src/types/Items.ts
  src/types/index.ts
  src/utils/writerColor.ts
Labels: ✨ Type: Feature

#10 Add HomePage
  package.json
  src/assets/png/Dotori3D.png
  src/assets/png/Dotori3DDark.png
  src/assets/svg/CameraIcon.tsx
  src/assets/svg/DefaultProfile.tsx
  src/assets/svg/LeftChevron.tsx
  src/assets/svg/MenubarIcon.tsx
  src/assets/svg/RightChevron.tsx
  src/assets/svg/XtextIcon.tsx
  src/assets/svg/index.ts
  src/components/Home/atoms/MenuOption/index.tsx
  src/components/Home/atoms/MenuOption/style.ts
  src/components/Home/atoms/ModalHeader/index.tsx
  src/components/Home/atoms/ModalHeader/style.ts
  src/components/Home/atoms/PenaltyItem/index.tsx
  src/components/Home/atoms/PenaltyItem/style.ts
  src/components/Home/atoms/Wrapper/style.ts
  src/components/Home/molecules/ApplyBox/index.tsx
  src/components/Home/molecules/ApplyBox/style.ts
  src/components/Home/molecules/MenuModal/index.tsx
  src/components/Home/molecules/MenuModal/style.ts
  src/components/Home/molecules/PenaltyModal/index.tsx
  src/components/Home/molecules/PenaltyModal/style.ts
  src/components/Home/molecules/ProfileImgModal/index.tsx
  src/components/Home/molecules/ProfileImgModal/style.ts
  src/components/Home/organisms/MassageBoard/index.tsx
  src/components/Home/organisms/MealBoard/index.tsx
  src/components/Home/organisms/MealBoard/style.ts
  src/components/Home/organisms/NoticeBoard/index.tsx
  src/components/Home/organisms/NoticeBoard/style.ts
  src/components/Home/organisms/Profile/index.tsx
  src/components/Home/organisms/Profile/style.ts
  src/components/Home/organisms/SelfStudyBoard/index.tsx
  src/components/Home/organisms/TimeBoard/index.tsx
  src/components/Home/organisms/TimeBoard/style.ts
  src/components/Home/organisms/index.ts
  src/components/Home/templates/HomeTemplates/style.ts
  src/pages/index.tsx
  src/types/Home.ts
  src/types/Modals.ts
  src/types/index.ts
  src/utils/canvas.ts
  yarn.lock
Labels: ✨ Type: Feature

#11 Fix homePage url
  src/assets/data/SidebarMenuData.ts
  src/components/Common/atoms/Buttons/LogoutButton/index.tsx
  src/components/Common/organisms/Sidebar/index.tsx
  src/components/SignIn/organisms/SignInForm/index.tsx
  src/pages/home.tsx
  src/pages/index.tsx
Labels: 🔨 Type: Refector

#13 Add 비밀번호 변경 페이지
  src/api/member.ts
  src/components/ChangePasswd/organisms/ChangePasswdForm/index.tsx
  src/components/Common/atoms/Inputs/AuthInput/index.tsx
  src/components/Common/atoms/Inputs/AuthInput/style.ts
  src/components/SignUp/atoms/Wrapper/style.ts
  src/pages/changePasswd.tsx
  src/types/Forms.ts
  src/utils/Libs/requestUrls.ts
Labels: ✨ Type: Feature

#12 Update : noticeItem 속성
  src/components/Common/atoms/Items/NoticeItem/index.tsx
  src/components/Common/atoms/Items/NoticeItem/style.ts
  src/components/Home/organisms/NoticeBoard/index.tsx
  src/types/Items.ts
Labels: ✨ Type: Feature
