Repository Team-Ampersand/Dotori-client-v2, pull requests merged in 2023-08, with the labels that each got.

#203 Fix 공지사항 제목
  src/components/Notice/molecules/ContentHeader/index.tsx
  src/components/Notice/molecules/ContentHeader/style.ts
Labels: 🐞 Type: Bug, ⚡Type: Simple

#205 🔀 vh 반응형 단위 변경
  src/components/Common/atoms/Wrappers/CommonPageWrapper/style.ts
  src/components/Common/molecules/NullApplicationItem/style.ts
  src/components/Common/molecules/SearchFilter/style.ts
  src/components/Common/molecules/SidebarList/style.ts
  src/components/Common/organisms/CommonHeader/style.ts
  src/components/Common/organisms/NavigationDrawer/style.ts
  src/components/Common/organisms/Sidebar/style.ts
  src/components/Common/templates/AuthTemplates/style.ts
  src/components/Common/templates/MainTemplates/style.ts
  src/components/Home/molecules/ApplyBox/style.ts
  src/components/Home/organisms/MealBoard/style.ts
  src/components/Home/organisms/NoticeBoard/style.ts
  src/components/Home/organisms/Profile/style.ts
  src/components/Home/organisms/TimeBoard/style.ts
  src/components/Home/templates/HomeTemplates/style.ts
  src/components/Massage/organisms/MassageTable/style.ts
  src/components/NotFound/organisms/NotFoundOrganisms/style.ts
  src/components/Notice/templates/NoticeTemplate/style.ts
  src/components/Penalty/molecules/PenaltyRecordModal/style.ts
  src/components/Penalty/organisms/PenaltyTable/style.ts
  src/components/Penalty/templates/PenaltyTemplates/style.ts
  src/components/Promotion/molecules/DecsPart/style.ts
  src/components/Promotion/molecules/LoadingPart/style.ts
  src/components/Promotion/organisms/PromotionOrganisms/style.ts
  src/components/Promotion/templates/PromotionTemplates/style.ts
  src/components/SelfStudy/organisms/SelfStudyTable/style.ts
  src/components/SelfStudy/templates/SelfstudyTemplates/style.ts
Labels: ⚡Type: Simple

#207 🔀 공지사항 ContentWrapper수정 & 제목 width 수정
  src/components/Notice/organisms/NoticeContent/style.ts
Labels: ⚡Type: Simple

#209 🔀 공지사항 제목 길이 수정
  src/components/Notice/molecules/ContentHeader/style.ts
Labels: ⚡Type: Simple

#206 🔀 기자위, 개발자 권한에서 인원 수정 기능
  src/assets/svg/SettingIcon.tsx
  src/assets/svg/index.ts
  src/components/Home/molecules/ApplyBox/index.tsx
  src/components/Home/molecules/ApplyBox/style.ts
  src/components/Home/organisms/MassageBoard/index.tsx
  src/components/Home/organisms/SelfStudyBoard/index.tsx
  src/types/Home.ts
Labels: 🎨 Type: Publishing, 🪛 Type: Performance

#210 🔀 Deploy
  .github/CODEOWNERS
  src/assets/svg/SettingIcon.tsx
  src/assets/svg/index.ts
  src/components/Common/atoms/Wrappers/CommonPageWrapper/style.ts
  src/components/Common/molecules/NullApplicationItem/style.ts
  src/components/Common/molecules/SearchFilter/style.ts
  src/components/Common/molecules/SidebarList/style.ts
  src/components/Common/organisms/CommonHeader/style.ts
  src/components/Common/organisms/NavigationDrawer/style.ts
  src/components/Common/organisms/Sidebar/style.ts
  src/components/Common/templates/AuthTemplates/style.ts
  src/components/Common/templates/MainTemplates/style.ts
  src/components/Home/molecules/ApplyBox/index.tsx
  src/components/Home/molecules/ApplyBox/style.ts
  src/components/Home/molecules/PenaltyModal/style.ts
  src/components/Home/organisms/MassageBoard/index.tsx
  src/components/Home/organisms/MealBoard/style.ts
  src/components/Home/organisms/NoticeBoard/style.ts
  src/components/Home/organisms/Profile/style.ts
  src/components/Home/organisms/SelfStudyBoard/index.tsx
  src/components/Home/organisms/TimeBoard/style.ts
  src/components/Home/templates/HomeTemplates/style.ts
  src/components/Massage/organisms/MassageTable/style.ts
  src/components/NotFound/organisms/NotFoundOrganisms/style.ts
  src/components/Notice/molecules/ContentHeader/style.ts
  src/components/Notice/organisms/NoticeContent/style.ts
  src/components/Notice/templates/NoticeTemplate/style.ts
  src/components/Penalty/molecules/PenaltyListModal/style.ts
  src/components/Penalty/molecules/PenaltyRecordModal/style.ts
  src/components/Penalty/organisms/PenaltyTable/style.ts
  src/components/Penalty/templates/PenaltyTemplates/style.ts
  src/components/Promotion/molecules/DecsPart/style.ts
  src/components/Promotion/molecules/LoadingPart/style.ts
  src/components/Promotion/organisms/PromotionOrganisms/style.ts
  src/components/Promotion/templates/PromotionTemplates/style.ts
  src/components/SelfStudy/organisms/SelfStudyTable/style.ts
  src/components/SelfStudy/templates/SelfstudyTemplates/style.ts
  src/types/Home.ts
Labels: 🌏 Type: Deploy

#212 🔀 기상음악 섬네일 주소 변경
  src/components/Song/molecules/SongItem/index.tsx
Labels: 3️⃣ Priority: Low, ⚡Type: Simple

#213 🔀 Deploy
  src/components/Song/molecules/SongItem/index.tsx
Labels: 🌏 Type: Deploy
