Repository Team-Ampersand/Dotori-client-v2, pull requests merged in 2024-02, with the labels that each got.

#237 🔀 24학년도 신입생 이메일 검증 추가
  src/components/Common/molecules/EmailCheck/index.tsx
Labels: 0️⃣ Priority: Critical, ⚡Type: Simple

#238 🔀 Deploy
  src/api/member.ts
  src/api/stuInfo.ts
  src/assets/svg/DefaultProfile.tsx
  src/components/Common/atoms/Items/FilterItem/index.tsx
  src/components/Common/molecules/ApplicationItem/index.tsx
  src/components/Common/molecules/EmailCheck/index.tsx
  src/components/Common/molecules/SearchFilter/index.tsx
  src/components/Home/atoms/MenuOption/style.ts
  src/components/Home/atoms/Script/SomeScript.tsx
  src/components/Home/molecules/MenuModal/index.tsx
  src/components/Home/molecules/ProfileImgModal/index.tsx
  src/components/Home/molecules/ProfileImgModal/style.ts
  src/components/Home/organisms/Profile/index.tsx
  src/components/Home/organisms/Profile/style.ts
  src/components/Home/organisms/TimeBoard/index.tsx
  src/components/Home/organisms/TimeBoard/style.ts
  src/components/Massage/molecules/MassageList/index.tsx
  src/components/SelfStudy/molecules/SelfStudyList/index.tsx
  src/components/StuInfo/molecules/EditInput/index.tsx
  src/components/StuInfo/molecules/EditInput/style.ts
  src/components/StuInfo/molecules/EditRadioBtn/index.tsx
  src/components/StuInfo/molecules/EditRadioBtn/style.ts
  src/components/StuInfo/molecules/StuInfoItem/index.tsx
  src/components/StuInfo/molecules/StuInfoItem/style.ts
  src/components/StuInfo/organisms/EditModal/index.tsx
  src/components/StuInfo/organisms/EditModal/style.ts
  src/components/StuInfo/organisms/StuInfoList/index.tsx
  src/types/Filter.ts
  src/types/Home.ts
  src/types/List.ts
  src/types/Massage.ts
  src/types/Modals.ts
  src/types/Selfstudy.ts
  src/types/components/StuInfoPage.ts
  src/utils/ChangeProfileModalcon.tsx
  src/utils/Libs/requestUrls.ts
  src/utils/canvas.ts
Labels: 🌏 Type: Deploy

#239 🔀 프로필 사진 삭제 후처리 및 학생정보 페이지 프로필 이미지 노출
  src/assets/svg/CircleDefaultProfile.tsx
  src/assets/svg/index.ts
  src/components/Home/molecules/ProfileImgModal/index.tsx
  src/components/Home/organisms/Profile/style.ts
  src/components/StuInfo/molecules/StuInfoItem/index.tsx
  src/components/StuInfo/molecules/StuInfoItem/style.ts
Labels: 🎨 Type: Publishing, 🪛 Type: Performance
