Repository Team-Ampersand/Dotori-client-v2, pull requests merged in 2024-06, with the labels that each got.

#262 🔀 나이스 meal api 통신 수정
  src/components/Home/organisms/MealBoard/index.tsx
  src/types/Meal.ts
Labels: 🐞 Type: Bug, 📬 Type: API, 🪛 Type: Performance

#263 🔀 react-toastify custom hooks 제작
  src/hooks/useToastify.ts
  src/pages/_app.tsx
Labels: ✨ Type: Feature

#264 🔀 모바일 화면의 음악 삭제 버튼 권한 부여
  src/components/Song/molecules/ResponsiveModal/index.tsx
  src/components/Song/molecules/SongItem/index.tsx
  src/types/Modals.ts
Labels: 🐞 Type: Bug, 2️⃣ Priortiy: Medium

#265 🔀 캘린더의 날짜 버튼 삭제
  src/components/Common/atoms/Calendar/style.ts
Labels: 3️⃣ Priority: Low, ⚡Type: Simple, 🎨 Type: Publishing
