Repository Team-Ampersand/Dotori-client-v2, pull requests merged in 2024-07, with the labels that each got.

#266 🔀 캘린더의 달 변경 불가
  src/components/Common/atoms/Calendar/style.ts
Labels: 3️⃣ Priority: Low, ⚡Type: Simple

#254 :bug: Fix warning
  src/api/notice.ts
  src/components/Notice/organisms/NoticeContent/index.tsx
  src/components/Notice/organisms/NoticeList/index.tsx
Labels: ⚡Type: Simple

#267 🔀Deploy
  next.config.js
  package.json
  src/api/notice.ts
  src/components/Common/atoms/Calendar/style.ts
  src/components/Home/organisms/MassageBoard/index.tsx
  src/components/Home/organisms/MealBoard/index.tsx
  src/components/Notice/organisms/NoticeContent/index.tsx
  src/components/Notice/organisms/NoticeList/index.tsx
  src/components/Song/molecules/ResponsiveModal/index.tsx
  src/components/Song/molecules/SongForm/index.tsx
  src/components/Song/molecules/SongItem/index.tsx
  src/hooks/useToastify.ts
  src/pages/_app.tsx
  src/types/Home.ts
  src/types/Meal.ts
  src/types/Modals.ts
  yarn.lock
Labels: 🌏 Type: Deploy

#271 🔀 사이드바 반응형 문제 해결
  src/pages/notice/[boardId].tsx
  src/pages/notice/index.tsx
Labels: 🐞 Type: Bug, 3️⃣ Priority: Low, 🎨 Type: Publishing

#272 🔀 프로필 이미지 수정,추가 메시지 문제 해결
  src/components/Home/molecules/ProfileImgModal/index.tsx
Labels: 🐞 Type: Bug, 3️⃣ Priority: Low
