Repository Team-Ampersand/Dotori-client-v2, pull requests merged in 2024-04, with the labels that each got.

#246 🔀 나이스 API KEY 감추기
  next.config.js
  src/components/Home/organisms/MealBoard/index.tsx
Labels: 🪛 Type: Performance

#247 🔀 Deploy
  next.config.js
  src/components/Home/organisms/MealBoard/index.tsx
  src/components/Notice/molecules/ContentHeader/index.tsx
  src/components/Notice/molecules/ContentHeader/style.ts
Labels: 🌏 Type: Deploy

#250 🔀 youtude api key 노출 방지
  src/components/Song/molecules/SongItem/index.tsx
  src/types/components/SongPage.ts
Labels: 1️⃣ Priority: High

#251 🔀 도토리 다중 음악 신청 방지
  src/components/Song/molecules/SongForm/index.tsx
  src/components/Song/molecules/SongForm/style.ts
Labels: 🐞 Type: Bug, 1️⃣ Priority: High, 🎨 Type: Publishing

#252 🔀Deploy
  .github/delete_merged_branch-config.yml
  .github/workflows/DOTORI_CI.yml
  src/api/notice.ts
  src/components/Song/molecules/SongForm/index.tsx
  src/components/Song/molecules/SongForm/style.ts
  src/components/Song/molecules/SongItem/index.tsx
  src/types/components/SongPage.ts
Labels: 🌏 Type: Deploy
