Repository Team-Ampersand/Dotori-client-v2, pull requests merged in 2024-01, with the labels that each got.

#227 🔀 권한 가져오기 방식 변경
  src/types/Role.ts
  src/utils/Libs/getRole.ts
Labels: 🐞 Type: Bug, 0️⃣ Priority: Critical

#229 🔀 input 스타일 수정
  src/components/Common/atoms/Inputs/AuthInput/style.ts
  src/components/Common/molecules/EmailCheck/index.tsx
  src/components/Home/molecules/ProfileImgModal/index.tsx
  src/components/StuInfo/organisms/EditModal/style.ts
  src/styles/globals.tsx
Labels: ⚡Type: Simple, 🎨 Type: Publishing

#230 🔀 토큰 재발급 헤더 수정
  src/api/member.ts
Labels: 🐞 Type: Bug, 0️⃣ Priority: Critical, ⚡Type: Simple

#231 🔀 급식 시간에 맞는 식단표 띄우기
  src/components/Home/organisms/MealBoard/index.tsx
Labels: 🐞 Type: Bug, 1️⃣ Priority: High

#232 🔀 자습 신청 마지막 순위 스탬프 아이콘 표시
  src/components/Common/molecules/ApplicationItem/index.tsx
  src/components/SelfStudy/molecules/SelfStudyList/index.tsx
  src/types/List.ts
Labels: 🐞 Type: Bug, 3️⃣ Priority: Low, ⚡Type: Simple

#233 🔀 Deploy
  src/api/member.ts
  src/components/Common/atoms/Inputs/AuthInput/style.ts
  src/components/Common/molecules/ApplicationItem/index.tsx
  src/components/Common/molecules/EmailCheck/index.tsx
  src/components/Home/molecules/ProfileImgModal/index.tsx
  src/components/Home/organisms/MealBoard/index.tsx
  src/components/SelfStudy/molecules/SelfStudyList/index.tsx
  src/components/StuInfo/organisms/EditModal/style.ts
  src/styles/globals.tsx
  src/types/List.ts
Labels: 🌏 Type: Deploy

#234 🔀 프로필 사진 기능 구현
  src/api/member.ts
  src/assets/svg/DefaultProfile.tsx
  src/components/Common/atoms/Items/FilterItem/index.tsx
  src/components/Common/molecules/ApplicationItem/index.tsx
  src/components/Common/molecules/SearchFilter/index.tsx
  src/components/Home/atoms/MenuOption/style.ts
  src/components/Home/atoms/Script/SomeScript.tsx
  src/components/Home/molecules/MenuModal/index.tsx
  src/components/Home/molecules/ProfileImgModal/index.tsx
  src/components/Home/molecules/ProfileImgModal/style.ts
  src/components/Home/organisms/Profile/index.tsx
  src/components/Home/organisms/Profile/style.ts
  src/components/Home/organisms/TimeBoard/index.tsx
  src/components/Home/organisms/TimeBoard/style.ts
  src/components/Massage/molecules/MassageList/index.tsx
  src/components/SelfStudy/molecules/SelfStudyList/index.tsx
  src/components/StuInfo/molecules/EditRadioBtn/index.tsx
  src/components/StuInfo/molecules/StuInfoItem/index.tsx
  src/components/StuInfo/molecules/StuInfoItem/style.ts
  src/components/StuInfo/organisms/EditModal/index.tsx
  src/components/StuInfo/organisms/StuInfoList/index.tsx
  src/types/Filter.ts
  src/types/Home.ts
  src/types/List.ts
  src/types/Massage.ts
  src/types/Modals.ts
  src/types/Selfstudy.ts
  src/types/components/StuInfoPage.ts
  src/utils/ChangeProfileModalcon.tsx
  src/utils/Libs/requestUrls.ts
  src/utils/canvas.ts
Labels: ✨ Type: Feature, 1️⃣ Priority: High, 🎨 Type: Publishing, 🪛 Type: Performance

#236 🔀 프로필 사진 변경 후 처리 로직 수정
  src/components/Home/molecules/ProfileImgModal/index.tsx
Labels: 3️⃣ Priority: Low, 🔨 Type: Refector, 🪛 Type: Performance

#235 🔀 학생 정보 수정 api 파라미터 변경 및 스타일 수정
  src/api/stuInfo.ts
  src/components/StuInfo/molecules/EditInput/index.tsx
  src/components/StuInfo/molecules/EditInput/style.ts
  src/components/StuInfo/molecules/EditRadioBtn/index.tsx
  src/components/StuInfo/molecules/EditRadioBtn/style.ts
  src/components/StuInfo/organisms/EditModal/index.tsx
  src/components/StuInfo/organisms/EditModal/style.ts
  src/types/components/StuInfoPage.ts
Labels: 🐞 Type: Bug, 1️⃣ Priority: High, ⚡Type: Simple, 🎨 Type: Publishing
