Repository Team-Ampersand/Dotori-client-v2, pull requests merged in 2024-05, with the labels that each got.

#253 번틀 사이즈 최적화
  next.config.js
  package.json
  yarn.lock
Labels: 🔨 Type: Refector

#256 :bug: Fix duplication export
  next.config.js
Labels: 🐞 Type: Bug

#259 🔀 다중 음악 방지 방식 isSubmitting 사용
  src/components/Song/molecules/SongForm/index.tsx
Labels: 🔨 Type: Refector, 🪛 Type: Performance

#260 🔀 여자일 때는 마사지 신청 불가로 상태 변경
  src/components/Home/organisms/MassageBoard/index.tsx
  src/types/Home.ts
Labels: 🪛 Type: Performance
