Repository Team-Ampersand/Dotori-client-v2, pull requests merged in 2024-08, with the labels that each got.

#276 🔀: 토큰 만료일 지정 코드 추가
  src/api/member.ts
  src/utils/Libs/getToken.ts
  src/utils/Libs/logout.ts
  src/utils/Libs/setToken.ts
Labels: 1️⃣ Priority: High

#275 🔀 토큰 오염시 리프래쉬 문제 해결
  src/components/Common/atoms/Calendar/style.ts
  src/utils/Libs/apiClient.ts
  src/utils/Libs/getCookie.ts
  src/utils/Libs/getRefresh.ts
Labels: 🐞 Type: Bug, 1️⃣ Priority: High, 📬 Type: API

#277 Revert "🔀 토큰 오염시 리프래쉬 문제 해결"
  src/components/Common/atoms/Calendar/style.ts
  src/utils/Libs/apiClient.ts
  src/utils/Libs/getCookie.ts
  src/utils/Libs/getRefresh.ts
Labels: 🐞 Type: Bug, 1️⃣ Priority: High

#279 🔀 프로필 이미지 확장자를 서버에서 확인할 수 있도록 변경
  src/utils/canvas.ts
Labels: 🐞 Type: Bug, 1️⃣ Priority: High

#280 🔀토큰 오염 에러 해결
  src/api/member.ts
  src/utils/Libs/apiClient.ts
  src/utils/Libs/getRefresh.ts
  src/utils/Libs/getToken.ts
Labels: 🐞 Type: Bug, 1️⃣ Priority: High

#282 🔀Deploy
  src/api/member.ts
  src/components/Home/molecules/ProfileImgModal/index.tsx
  src/pages/notice/[boardId].tsx
  src/pages/notice/index.tsx
  src/utils/Libs/apiClient.ts
  src/utils/Libs/getRefresh.ts
  src/utils/Libs/getToken.ts
  src/utils/Libs/logout.ts
  src/utils/Libs/setToken.ts
  src/utils/canvas.ts
Labels: 2️⃣ Priortiy: Medium

#283 🔀newAuthorization undefined 예외 처리 진행
  src/api/member.ts
  src/utils/Libs/apiClient.ts
  src/utils/Libs/getRefresh.ts
  src/utils/Libs/getToken.ts
Labels: 🐞 Type: Bug, 1️⃣ Priority: High

#284 🔀Deploy
  src/api/member.ts
  src/utils/Libs/apiClient.ts
  src/utils/Libs/getRefresh.ts
  src/utils/Libs/getToken.ts
Labels: 🌏 Type: Deploy

#287 🔀 Deploy
  src/components/Song/molecules/NoticeModal/index.tsx
Labels: 🌏 Type: Deploy

#288 🔀header에 자동으로 accessToken이 삽입되지 않아 모든 통신에서 401이 뜨는 문제 해결
  src/utils/Libs/apiClient.ts
  src/utils/Libs/getRefresh.ts
  src/utils/Libs/setHeader.ts
Labels: 🐞 Type: Bug, 1️⃣ Priority: High, 📬 Type: API

#289 🔀 Deploy
  src/utils/Libs/apiClient.ts
  src/utils/Libs/getRefresh.ts
  src/utils/Libs/setHeader.ts
Labels: 🌏 Type: Deploy
